spring.application.name=backend
server.port=8080

# Configuración de Base de Datos MySQL
# IMPORTANTE: Asegúrate de crear una base de datos llamada 'brickcollector' en tu MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/brickcollector?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate: Crea/actualiza las tablas automáticamente al arrancar en base a nuestras Clases Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Claves de APIs Externas
api.rebrickable.key=f138411743940f84bc3cd94fbdc27848
api.brickset.key=3-LGV1-yqYd-6mSYx

# Configuración JWT (Firma de tokens de sesión)
jwt.secret=MySuperSecretKeyForBrickCollectorApp20261234567890
jwt.expiration=86400000
